name: GitHub Metrics

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest

    steps:
      - name: Languages and lines
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_lines: true

          plugin_languages: true
          plugin_languages_aliases: javascript:JS typescript:TS
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_analysis_timeout: 15

      - name: Recently used languages
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.lines.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_languages: true
          plugin_languages_sections: recently-used

          # 400 eventos como máximo
          plugin_languages_recent_load: 400

          # Últimos 14 días
          plugin_languages_recent_days: 14
