name: WakaTime Stats

on:
  schedule:
    # Se ejecuta automáticamente todos los días a la medianoche UTC
    - cron: '0 0 * * *'
  # Te permite activarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "⣿⣾⣿⣽⣻⢿⡿⣟⣯⢿"
          #IGNORED_LANGUAGES: "Other"
          TIME_RANGE: "all_time"
          LANG_COUNT: 20
          SHOW_TIME: false
          SHOW_TOTAL: true
          CODE_LANG: python # optional
